import { Application } from "./types";

export const applications: Application[] = [
  {
    name: "Tome",
    foundAt: "wellfound",
    role: "Full-Stack Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=1611101",
    status: "Applied",
    appliedAt: "6/27/24",
    salary: {
      min: 100000,
      max: 150000,
    },
  },
  {
    name: "Equi",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=3041571",
    status: "Applied",
    appliedAt: "6/27/24",
    salary: {
      min: 160000,
      max: 180000,
    },
  },
  {
    name: "Trainwell",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=3041571",
    status: "Applied",
    appliedAt: "6/27/24",
    salary: {
      min: 175000,
      max: 200000,
    },
  },
  {
    name: "Seeds",
    foundAt: "wellfound",
    role: "Senior Full Stack Developer",
    website: "https://wellfound.com/jobs?job_listing_id=3041883",
    status: "Applied",
    appliedAt: "6/27/24",
    salary: {
      min: 140000,
      max: 185000,
    },
  },
  {
    name: "Mouser",
    foundAt: "direct",
    role: "Sr Web Developer",
    website: "https://careers.mouser.com/jobs/17411?lang=en-us",
    status: "Applied",
    appliedAt: "6/27/24",
  },
  {
    name: "Murata Machinery Usa Inc.",
    foundAt: "indeed",
    role: "Senior Software Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/27/24",
  },
  {
    name: "Robert Half",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/26/24",
  },
  {
    name: "WambaTech",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/26/24",
  },
  {
    name: "Tamnoon",
    foundAt: "linkedin",
    role: "Backend Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/26/24",
  },
  {
    name: "CRG",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/26/24",
    salary: {
      min: 120000,
      max: 120000,
    },
  },
  {
    name: "IntePros",
    foundAt: "linkedin",
    role: ".Net Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/26/24",
    salary: {
      min: 100000,
      max: 115000,
    },
  },
  {
    name: "PDI Technologies",
    foundAt: "direct",
    role: "Software Engineer III",
    website: "https://pdi.applytojob.com/apply/jobs/details/gg9xSu3OUs?&",
    status: "Applied",
    appliedAt: "6/26/24",
    salary: {
      min: 90000,
      max: 1000000,
    },
  },
  {
    name: "PDI Technologies",
    foundAt: "direct",
    role: "Software Engineer III",
    website: "https://pdi.applytojob.com/apply/jobs/details/u37b6Cl2Av?&",
    status: "Applied",
    appliedAt: "6/26/24",
    salary: {
      min: 80000,
      max: 1100000,
    },
  },
  {
    name: "PDI Technologies",
    foundAt: "direct",
    role: "Software Engineer II",
    website: "https://pdi.applytojob.com/apply/jobs/details/WIYduBQbSC?&",
    status: "Applied",
    appliedAt: "6/26/24",
    salary: {
      min: 70000,
      max: 80000,
    },
  },
  {
    name: "PDI Technologies",
    foundAt: "direct",
    role: "Software Engineer II",
    website: "https://pdi.applytojob.com/apply/jobs/details/xBisnDCwKK?&",
    status: "Applied",
    appliedAt: "6/26/24",
    salary: {
      min: 90000,
      max: 100000,
    },
  },
  {
    name: "Software Technology Inc.",
    foundAt: "linkedin",
    role: "Full Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Storable",
    foundAt: "linkedin",
    role: "Software Engineer II",
    website: "https://www.linkedin.com",
    notes: "set asking salary range to 105k-120k",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 95000,
      max: 148000,
    },
  },
  {
    name: "Bitcoin Devs Company",
    foundAt: "linkedin",
    role: "Full Stack Engineer - Node.js, React (USA Based, 100% Remote)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 80000,
      max: 120000,
    },
  },
  {
    name: "Health Universe, Inc",
    foundAt: "linkedin",
    role: "Full Stack Engineer (Next)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 160000,
    },
  },
  {
    name: "React Developer",
    foundAt: "linkedin",
    role: "React Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 80000,
      max: 110000,
    },
  },
  {
    name: "TekJobs",
    foundAt: "linkedin",
    role: ".Net Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "CRG",
    foundAt: "linkedin",
    role: "Front-End Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 100000,
    },
  },
  {
    name: "Themesoft Inc.",
    foundAt: "linkedin",
    role: "Frontend Developer III",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Hampton North",
    foundAt: "linkedin",
    role: "Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 110000,
      max: 125000,
    },
  },
  {
    name: "PDI Technologies",
    foundAt: "linkedin",
    role: "Software Engineer II",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 70000,
      max: 80000,
    },
  },
  {
    name: "RedStream Technology",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Tailored Management",
    foundAt: "linkedin",
    role: "Web Developer IV",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 190000,
      max: 190000,
    },
  },
  {
    name: "Episki",
    foundAt: "linkedin",
    role: "Front End Developer",
    website: "https://episki.homerun.co/front-end-developer/en",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 72000,
      max: 90000,
    },
  },
  {
    name: "HX5, LLC",
    foundAt: "linkedin",
    role: "Software Engineer",
    notes: "on-site in ogden",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Harvey Nash",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 150000,
      max: 160000,
    },
  },
  {
    name: "Milestone Technologies, Inc.",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 150000,
    },
  },
  {
    name: "Addison Group",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 108000,
    },
  },
  {
    name: "Optomi",
    foundAt: "linkedin",
    role: "Senior Software Engineer (Node.js, NestJS, GraphQL) - 100% Remote",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Understanding Recruitment",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 160000,
      max: 200000,
    },
  },
  {
    name: "MMD Services",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 160000,
    },
  },
  {
    name: "Green Key Resources",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 120000,
      max: 180000,
    },
  },
  {
    name: "Invitae",
    foundAt: "linkedin",
    role: "Sr. Full Stack Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 138400,
      max: 173000,
    },
  },
  {
    name: "Arrow Search Partners",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 150000,
      max: 250000,
    },
  },
  {
    name: "Fleek",
    foundAt: "linkedin",
    role: "Sr. Backend Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Lappo",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "InterEx Group",
    foundAt: "linkedin",
    role: "Cloud Backend Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "eNGINE",
    foundAt: "linkedin",
    role: "Integration Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 175000,
      max: 225000,
    },
  },
  {
    name: "Sift AI",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Eliassen Group",
    foundAt: "linkedin",
    role: "Senior Web API Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 100000,
    },
  },
  {
    name: "Virginia Tech",
    foundAt: "linkedin",
    role: "Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Realm",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 150000,
      max: 200000,
    },
  },
  {
    name: "Cypress HCM",
    foundAt: "linkedin",
    role: "Frontend Web Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 132000,
      max: 145000,
    },
  },
  {
    name: "Resonance Security",
    foundAt: "linkedin",
    role: "Senior Software Development Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Phaxis",
    foundAt: "linkedin",
    role: "Sr Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 190000,
    },
  },
  {
    name: "Confidential",
    foundAt: "linkedin",
    role: "Senior Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Ambry Genetics",
    foundAt: "linkedin",
    role: "Software Engineer II-Remote, USA",
    website: "https://www.linkedin.com",
    notes: "set expected to 115k",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 105000,
      max: 120000,
    },
  },
  {
    name: "SoFi",
    foundAt: "linkedin",
    role: "Senior Software Engineer, Invest",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 128000,
      max: 240000,
    },
  },
  {
    name: "Kforce Inc",
    foundAt: "linkedin",
    role: "Full Stack C# Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 120000,
    },
  },
  {
    name: "Kronkite",
    foundAt: "linkedin",
    role: "Lead Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "GibsonAI",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 140000,
      max: 175000,
    },
  },
  {
    name: "Eliassen Group",
    foundAt: "linkedin",
    role: "Senior Node.js Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 150000,
      max: 150000,
    },
  },
  {
    name: "Tokio Marine North American Services",
    foundAt: "linkedin",
    role: "Programmer III",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 89000,
      max: 130000,
    },
  },
  {
    name: "Jones Networking",
    foundAt: "linkedin",
    role: "Senior Programmer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 120000,
    },
  },
  {
    name: "Norwegian Cruise Line Holdings Ltd.",
    foundAt: "linkedin",
    role: "Senior Web Appliation Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "BlueScope Buildings North America, Inc.",
    foundAt: "linkedin",
    role: "Software Enginer IV",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Brady Corporation",
    foundAt: "linkedin",
    role: "Software Engineer",
    notes: "hybrid",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Conexess Group",
    foundAt: "linkedin",
    role: "Full Stack Engineer (Typescript, React, Node.js, Espress.js, Backstage.io) Remote",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Aristotle",
    foundAt: "linkedin",
    role: ".Net Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Aristotle",
    foundAt: "linkedin",
    role: ".Net Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Stellar Global Solutions",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Insight Global",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 150000,
    },
  },
  {
    name: "Reebelo",
    foundAt: "linkedin",
    role: "Senior Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 120000,
      max: 150000,
    },
  },
  {
    name: "Yum! Brands",
    foundAt: "linkedin",
    role: "Sr Backend Engineer II",
    website:
      "https://jobs.yum.com/jobs/general/united-states/sr-software-engineer-ii/3165?utm_source=linkedin&utm_medium=referral&utm_campaign=jobboard&group=1583#/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 124100,
      max: 171050,
    },
  },
  {
    name: "Groove Jones",
    foundAt: "linkedin",
    role: "Back End Developer (Contract)",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Smart Bot Systems LLC",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Storable",
    foundAt: "linkedin",
    role: "Sr. Software Engineer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 120000,
      max: 135000,
    },
  },
  {
    name: "HomeCloud",
    foundAt: "linkedin",
    role: "AWS Developer (Node.js / Typescript / Serverless)",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 150000,
      max: 250000,
    },
  },
  {
    name: "Marchex",
    foundAt: "direct",
    role: "Software Development Engineer",
    website: "https://www.marchex.com/about-us/careers/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 65000,
      max: 85000,
    },
  },
  {
    name: "Vantiva",
    foundAt: "linkedin",
    role: "Software Engineer, Web and Mobile",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Panoptyc",
    foundAt: "linkedin",
    role: "Senior Full Stack Developer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 175000,
      max: 175000,
    },
  },
  {
    name: "iMatch Technical Services",
    foundAt: "linkedin",
    role: "Senior Engineer - Search",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 180000,
    },
  },
  {
    name: "Kavaliro",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 100000,
      max: 120000,
    },
  },
  {
    name: "Harnham",
    foundAt: "linkedin",
    role: "API Engineer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 140000,
      max: 140000,
    },
  },
  {
    name: "TranscendAP",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "ProSearch",
    foundAt: "linkedin",
    role: "Sr. Software Engineer (.NET MAUI)",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
  },
  {
    name: "Planned Parenthood Direct, Inc.",
    foundAt: "linkedin",
    role: "Senior Full Stack Software Engineer",
    website: "https://careers.hireology.com/ppdirect/1865257/description",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 135000,
      max: 140000,
    },
  },
  {
    name: "Eliassen Group",
    foundAt: "linkedin",
    role: ".Net Developer/Architect (Remote)",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 156000,
    },
  },
  {
    name: "Prosum",
    foundAt: "linkedin",
    role: "Full Stack Engineer (Angular 12+, Serverless, AWS, Node, Graphql)",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 140000,
      max: 150000,
    },
  },
  {
    name: "Aries",
    foundAt: "linkedin",
    role: "Senior Frontend Developer",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 80000,
      max: 150000,
    },
  },
  {
    name: "Vertisystem",
    foundAt: "linkedin",
    role: "Senior Software Developer (C# with ASP.NET, .NET Core and Web APIs)",
    notes: "Hybrid work in SLC",
    website: "https://www.linkedin.com/",
    status: "Applied",
    appliedAt: "6/24/24",
    salary: {
      min: 130000,
      max: 140000,
    },
  },
  {
    name: "Focused Support LLC",
    foundAt: "indeed",
    role: "Mid-Level Software Engineer",
    website:
      "https://www.indeed.com/jobs?q=software+engineer&l=Ogden%2C+UT&radius=50&start=10&vjk=42f9e4fa7e689c44",
    status: "Applied",
    appliedAt: "6/21/24",
    salary: {
      min: 80000,
      max: 110000,
    },
  },
  {
    name: "AvantGuard Monitoring Centers",
    foundAt: "indeed",
    role: "Mid Level Software Engineer",
    website:
      "https://www.indeed.com/jobs?q=software+engineer&l=Ogden%2C+UT&from=searchOnHP&vjk=167661edadd2096a",
    status: "Applied",
    appliedAt: "6/21/24",
  },
  {
    name: "Xylem",
    foundAt: "linkedin",
    role: "Application Engineer",
    website:
      "https://careers-mtsi.icims.com/jobs/9046/full-stack-software-lead/candidate?csrf=2AD08AA3C109CA88&hashed=1274430067&uploadResume=1&uploadResume=1",
    status: "Applied",
    appliedAt: "6/21/24",
  },
  {
    name: "Full Stack Software Lead",
    foundAt: "linkedin",
    role: "Engineer",
    website:
      "https://careers-mtsi.icims.com/jobs/9046/full-stack-software-lead/candidate?csrf=2AD08AA3C109CA88&hashed=1274430067&uploadResume=1&uploadResume=1",
    status: "Applied",
    appliedAt: "6/21/24",
  },
  {
    name: "Air Force Civilian Service",
    foundAt: "direct",
    role: "Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/21/24",
    salary: {
      min: 54200,
      max: 97800,
    },
  },
  {
    name: "Talent Groups",
    foundAt: "direct",
    role: "Contract Web Application Developer",
    website:
      "https://www.talentgroups.com/job-details/contract-web-application-developer-in-softwareapplication-development-and-architecture-jobs-943647?key=linkedin",
    status: "Applied",
    appliedAt: "6/21/24",
    salary: {
      min: 90000,
      max: 130000,
    },
  },
  {
    name: "Continuum AI",
    foundAt: "linkedin",
    role: "Senior Full Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/21/24",
  },
  {
    name: "Payroll Integrations",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/21/24",
    salary: {
      min: 120000,
      max: 140000,
    },
  },
  {
    name: "Noxx AI",
    foundAt: "direct",
    role: "Backend Software Engineer",
    website:
      "https://talent.noxx.net/application/990e7fc6-be68-4a80-a797-6a1ff85a57c0",
    status: "Applied",
    appliedAt: "6/21/24",
  },
  {
    name: "Whitespectre",
    foundAt: "weworkremotely",
    role: "Senior Fullstack Engineer (React.js & Next.js)",
    website:
      "https://weworkremotely.com/remote-jobs/whitespectre-senior-fullstack-engineer-react-js-next-js",
    status: "Applied",
    appliedAt: "6/21/24",
  },
  {
    name: "Twilio",
    foundAt: "commitasync",
    role: "Software Enginer (L2)",
    website:
      "https://www.commitasync.com/jobs/software-engineer-l2-twilio-1718776216572/",
    status: "Applied",
    appliedAt: "6/21/24",
    salary: {
      min: 112000,
      max: 140000,
    },
  },
  {
    name: "Nymble Health",
    foundAt: "wellfound",
    role: "Mid-Level Full Stack Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=3021470",
    status: "Rejected",
    appliedAt: "6/20/24",
    rejectedAt: "6/27/24",
    salary: {
      min: 90000,
      max: 120000,
    },
  },
  {
    name: "Verdance",
    foundAt: "wellfound",
    role: "Fullstack Software Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=2465547",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 120000,
      max: 149000,
    },
  },
  {
    name: "RICEFW Technologies Inc",
    foundAt: "linkedin",
    role: "C# Software Developer",
    website: "https://linkedin.com/",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Opyn",
    foundAt: "wellfound",
    role: "Fullstack Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=2975364",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Toku",
    foundAt: "wellfound",
    role: "Full-Stack Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=3032711",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 120000,
      max: 170000,
    },
  },
  {
    name: "Sunbound",
    foundAt: "wellfound",
    role: "Full-Stack Junior Software Engineer",
    website:
      "https://wellfound.com/jobs/3039373-full-stack-junior-software-engineer",
    status: "Rejected",
    appliedAt: "6/20/24",
    rejectedAt: "6/20/24",
    salary: {
      min: 100000,
      max: 150000,
    },
  },
  {
    name: "Nametag",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer (Remote US)",
    website: "https://wellfound.com/jobs?job_listing_id=3038648",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 170000,
      max: 210000,
    },
  },
  {
    name: "Imprint Payments",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://wellfound.com/jobs",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 170000,
      max: 210000,
    },
  },
  {
    name: "Velvet",
    foundAt: "wellfound",
    role: "Software Engineer",
    website: "https://wellfound.com/jobs?job_listing_id=3035090",
    status: "Rejected",
    appliedAt: "6/20/24",
    rejectedAt: "6/27/24",
    salary: {
      min: 170000,
      max: 200000,
    },
  },
  {
    name: "Kunai",
    foundAt: "wellfound",
    role: "Backend Enginer (Python/Node/AWS)",
    website: "https://wellfound.com/jobs?job_listing_id=3029039",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 175000,
      max: 185000,
    },
  },
  {
    name: "Give Lively",
    foundAt: "wellfound",
    role: "Full Stack Engineer for Social Good",
    website: "https://wellfound.com/jobs?job_listing_id=95264",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 100000,
      max: 125000,
    },
  },
  {
    name: "Abridge",
    foundAt: "wellfound",
    role: "Senior Software Engineer (Full Stack)",
    website: "https://wellfound.com/jobs?job_listing_id=2991717",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 180000,
      max: 220000,
    },
  },
  {
    name: "Benchmark Analytics",
    foundAt: "linkedin",
    role: "Full-Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Keeper Security, Inc.",
    foundAt: "linkedin",
    role: "Senior Software Engineer, ReactJS",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Tebra",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Stanford Black Limited",
    foundAt: "linkedin",
    role: "React Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Solugenix",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "KODE Health",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Eliassen Group",
    foundAt: "linkedin",
    role: "Node/Typescript Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "TetraScience",
    foundAt: "linkedin",
    role: "Senior Software Engineer - Data Aquisition",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Harnham",
    foundAt: "linkedin",
    role: "API Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Microsoft",
    foundAt: "direct",
    role: "Software Engineer II (1721237)",
    website: "https://www.jobs.careers.microsoft.com",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 98300,
      max: 193200,
    },
  },
  {
    name: "Microsoft",
    foundAt: "direct",
    role: "Software Engineer II (1723116)",
    website: "https://www.jobs.careers.microsoft.com",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 98300,
      max: 193200,
    },
  },
  {
    name: "Microsoft",
    foundAt: "direct",
    role: "Software Engineer II (1729737)",
    website: "https://www.jobs.careers.microsoft.com",
    status: "Rejected",
    appliedAt: "6/20/24",
    rejectedAt: "6/21/24",
    salary: {
      min: 98300,
      max: 193200,
    },
  },
  {
    name: "Microsoft",
    foundAt: "direct",
    role: "Software Engineer II (1714323)",
    website: "https://www.jobs.careers.microsoft.com",
    status: "Applied",
    appliedAt: "6/20/24",
    salary: {
      min: 94300,
      max: 182600,
    },
  },
  {
    name: "Storm3",
    foundAt: "linkedin",
    role: "Senior Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Xorbix Technologies, Inc.",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Understanding Recruitment",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Rajant Corporation",
    foundAt: "linkedin",
    role: "Full Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Tier4 Group",
    foundAt: "linkedin",
    role: "Software Engineer (2323864)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Peak Partners",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Hamilton Porter",
    foundAt: "linkedin",
    role: "Software Architect",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "Pets Best Insurance Services, LLC",
    foundAt: "linkedin",
    role: "Web Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/20/24",
  },
  {
    name: "LogicGate",
    foundAt: "commitasync",
    role: "Software Engineer: Frontend",
    website:
      "https://www.commitasync.com/jobs/software-engineer-frontend-logicgate-1718171455876/",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Axon",
    foundAt: "commitasync",
    role: "Software Engineer",
    website:
      "https://www.commitasync.com/jobs/software-engineer-open-to-remote-work-axon-1718257839498/",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Spring Health",
    foundAt: "commitasync",
    role: "Senior Software Engineer II (Mobile + Web)",
    website:
      "https://www.commitasync.com/jobs/senior-software-engineer-ii-mobile-web-spring-health-1718257849732/",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Franklin Covey",
    foundAt: "commitasync",
    role: "Software Engineer",
    website:
      "https://www.commitasync.com/jobs/software-engineer-franklincovey-1718517014373/",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Trunk.io",
    foundAt: "commitasync",
    role: "Senior Software Engineer (Infrastructure)",
    website:
      "https://www.commitasync.com/jobs/senior-software-engineer-infrastructure-trunk-1718688007543/",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Apollo",
    foundAt: "commitasync",
    role: "Senior Software Engineer, Backend",
    website:
      "https://www.commitasync.com/jobs/senior-software-engineer-backend-apollo-graphql-1718688021084/",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Included Health",
    foundAt: "linkedin",
    role: "Senior Backend Engineer, Treat Team",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "IDR, Inc.",
    foundAt: "linkedin",
    role: "Python Developer (332492)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Mawson",
    foundAt: "linkedin",
    role: "DevOps Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Deep Sync",
    foundAt: "linkedin",
    role: "Software Engineer 2",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Oracle",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Westernacher Solutions",
    foundAt: "linkedin",
    role: "(Senior) Frontend Software Developer - eJustice",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Compunnel Inc.",
    foundAt: "linkedin",
    role: "DevOps Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Lumiere Systems",
    foundAt: "linkedin",
    role: "DevOps Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Akkodis",
    foundAt: "linkedin",
    role: "Java Application Developer - 100% Remote - Contract to Hire (W2)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Accroid Inc",
    foundAt: "linkedin",
    role: "Senior Developer/Programmer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "ITRAC Staffing",
    foundAt: "linkedin",
    role: "Mendix Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Linkfields Innovations (Pty) Ltd",
    foundAt: "linkedin",
    role: "Cloud Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Onestop Software",
    foundAt: "linkedin",
    role: "Next.JS Developer Freelance AI Sales Platform Development",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Montash",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Sela",
    foundAt: "linkedin",
    role: "Cloud Engineer II",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Optomi",
    foundAt: "linkedin",
    role: "Senior Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "HatchPros",
    foundAt: "linkedin",
    role: "React Developer (Frontend/UI/Redux)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Everbright",
    foundAt: "linkedin",
    role: "Software Dveloper II",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "MOGEL",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Insight Global",
    foundAt: "linkedin",
    role: "Data/Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "medQuest, Ltd.",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "LHH",
    foundAt: "linkedin",
    role: "Senior Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "GlobalPros.ai",
    foundAt: "linkedin",
    role: "Remote Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Tree Top Staffing, LLC",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Cyborgwave",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "KnowBe4",
    foundAt: "linkedin",
    role: "Software Enginer (Core) (Remote)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "RocketNode Hosting",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Parambil",
    foundAt: "linkedin",
    role: "Full Stack Web Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Sunnova Energy",
    foundAt: "linkedin",
    role: "Full Stack Developer II - React/.NET/C#",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "iMatch Technical Services",
    foundAt: "linkedin",
    role: "Software Engineer (.NET)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Space Executive",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Centific",
    foundAt: "linkedin",
    role: "Full Stack Developer (.NET, JavaScript)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Korn Ferry",
    foundAt: "linkedin",
    role: ".NET Developer (BBBH1666256)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Crypto Talent",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Oxenham Group",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Full Stack Engineer - Virtual Interlining",
    foundAt: "linkedin",
    role: "API Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Full Stack Engineer - Virtual Interlining",
    foundAt: "linkedin",
    role: "API Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Brooksource",
    foundAt: "linkedin",
    role: "API Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Brooksource",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Excelion Partners",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Multimedia Solutions",
    foundAt: "linkedin",
    role: "Web Developer - .NET CMS Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "EdgeCase Capital Partners",
    foundAt: "linkedin",
    role: "Database Programmer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Vangst",
    foundAt: "linkedin",
    role: "Senior Software Developer .NET Full-Stack",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Brillio",
    foundAt: "linkedin",
    role: "NodeJS/ReactJS FS developer - R01538391",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Rober Half",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Solu Technology Partners",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Braintrust",
    foundAt: "linkedin",
    role: "API Engineer - 587",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "True Group, Inc.",
    foundAt: "linkedin",
    role: ".NET Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "AshedIre Inc",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "IDR, Inc.",
    foundAt: "linkedin",
    role: "React Developer (9338779)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "MMD Services",
    foundAt: "linkedin",
    role: "Full Stack Engineer (React/Node) - Logistics",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Kress Designs Inc.",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Hopper",
    foundAt: "linkedin",
    role: "Software Developer, Full Stack/Mobile",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Strategic Employment Partners (SEP)",
    foundAt: "linkedin",
    role: "Fullstack .NET Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Recruiting From Scratch",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "rheumission",
    foundAt: "linkedin",
    role: "Full Stack Systems Engineer/Architect",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Tamnoon",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "22nd Century Technologies Inc.",
    foundAt: "linkedin",
    role: "Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "System Soft Technologies",
    foundAt: "linkedin",
    role: "Ecommerce Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Flintfox - Intelligent Pricing Platform",
    foundAt: "linkedin",
    role: ".NET Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Z. Wilson Talent Solutions",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Insurity",
    foundAt: "indeed",
    role: "Developer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Servpro",
    foundAt: "indeed",
    role: "Senior Developer",
    website: "https://www.indeed.com",
    status: "Rejected",
    rejectedAt: "6/20/24",
    appliedAt: "6/19/24",
  },
  {
    name: "EDZ Systems",
    foundAt: "indeed",
    role: "Site Reliability Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Northrop Grumman",
    foundAt: "indeed",
    role: "Sentinel Software Engineer",
    website: "https://www.indeed.com",
    status: "Rejected",
    rejectedAt: "6/20/24",
    appliedAt: "6/19/24",
  },
  {
    name: "Stratagen",
    foundAt: "indeed",
    role: "Software Developer 2",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "OneFifteen Recovery",
    foundAt: "indeed",
    role: "Senior Software Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Credit Corp Solutions",
    foundAt: "indeed",
    role: "Full Stack Developer - .Net",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "SOLUTIONREACH, INC.",
    foundAt: "indeed",
    role: "Principal Quality Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Talent Groups",
    foundAt: "linkedin",
    role: ".Net Developer (UT Residents Only)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Clicklease",
    foundAt: "indeed",
    role: "Software Architect",
    website: "https://www.indeed.com",
    status: "Rejected",
    appliedAt: "6/15/24",
    rejectedAt: "6/18/24",
  },
  {
    name: "Signify Technology",
    foundAt: "linkedin",
    role: "Senior Frontend Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Stealth",
    foundAt: "linkedin",
    role: "Backend Engineer - Node.js/TypeScript",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Cygnus Professionals Inc.",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Goliath Partners",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Torticity",
    foundAt: "linkedin",
    role: "Full Stack Javascript Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "MMD Services",
    foundAt: "linkedin",
    role: "Senior Full-Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Cart.com",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Empiric",
    foundAt: "linkedin",
    role: "Associate .Net Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Allyon, Inc.",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Kadince",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "ALIGNMT ai",
    foundAt: "linkedin",
    role: "Founding Software Engineer, Frontend",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "IntegraWeb Systems",
    foundAt: "linkedin",
    role: "Full Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Estes Group, LLC.",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Bigtoe Pose, Inc.",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Curate Partners",
    foundAt: "linkedin",
    role: "Full Stack Engineer (Data Science focus)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Saroe, Inc",
    foundAt: "linkedin",
    role: "Backend Integration Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "BlackLake Security",
    foundAt: "linkedin",
    role: "Senior Full-Stack Software Engineer - Contract",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Nelson Connects",
    foundAt: "linkedin",
    role: "Founding Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Fiori Technology Solutions Inc",
    foundAt: "linkedin",
    role: "C# Developer/Programmer Analyst",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Planet Technology",
    foundAt: "linkedin",
    role: "Developer Evangelist - Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Fieldwire",
    foundAt: "linkedin",
    role: "Mid-Level Frontend Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Verdantas",
    foundAt: "linkedin",
    role: "Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "VoteBud",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Clinical AI",
    foundAt: "linkedin",
    role: "Software Engineer I",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Entelli Consulting",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Tangerine Search Inc.",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Raydar",
    foundAt: "linkedin",
    role: "Solutions Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Plexus Resource Solutions",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Robert Half",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Associated Wholesale Grocers",
    foundAt: "linkedin",
    role: "SaaS Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Insight Global",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Cohere Health",
    foundAt: "linkedin",
    role: "Software Engineer II, Applications",
    website: "https://www.linkedin.com",
    status: "Rejected",
    appliedAt: "6/11/24",
    rejectedAt: "6/13/24",
  },
  {
    name: "Engtal",
    foundAt: "linkedin",
    role: "Entry Level Software Engineer (Remote)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Accelon Inc",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Alpine Solutions Group",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Dockyard, Inc",
    foundAt: "direct",
    role: "Senior Software Engineer (Typescript)",
    website:
      "https://dockyard.breezy.hr/p/94c49049786f-senior-software-engineer-typescript/apply/submitted",
    status: "Rejected",
    appliedAt: "6/11/24",
    rejectedAt: "6/13/24",
  },
  {
    name: "Canny",
    foundAt: "direct",
    role: "Software Engineer (Remote)",
    website:
      "https://careers.canny.io/o/software-engineer-remote-2-11/c/new?source=LinkedIn",
    status: "Assessment",
    appliedAt: "6/11/24",
    assessmentAt: "6/13/24",
    rejectedAt: "6/24/24",
  },
  {
    name: "Clickhouse",
    foundAt: "direct",
    role: "Full Stack Engineer - Billing (Remote)",
    website: "https://clickhouse.com/company/careers",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Clickhouse",
    foundAt: "direct",
    role: "Cloud Software Engineer, Developer Productivity- Remote",
    website: "https://clickhouse.com/company/careers",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Clublender",
    foundAt: "weworkremotely",
    role: "FullStack Software Developer",
    website:
      "https://weworkremotely.com/remote-jobs/clublender-inc-full-stack-web-developer-1",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Stratagen",
    foundAt: "indeed",
    role: "Software Developer 3",
    website: "https://www.indeed.com/cmp/Stratagen-1?attributionid=IAconfirm",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Thrive Market",
    foundAt: "commitasync",
    role: "Senior Software Engineer, Web",
    website: "https://thrivemarket.com/",
    status: "Rejected",
    appliedAt: "6/10/24",
    rejectedAt: "6/17/24",
  },
  {
    name: "Khan Academy",
    foundAt: "commitasync",
    role: "Software Engineer II, Data Infrastructure",
    website: "https://boards.greenhouse.io/khanacademy/jobs/6005599",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "KarmaCheck",
    foundAt: "indeed",
    role: "Sr Software Engineer - Frontend",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "L3Harris",
    foundAt: "indeed",
    role: "Specialist, Software Engineer",
    website:
      "https://careers.l3harris.com/job/-/-/4832/66137134304?jobPipeline=rd_indeed_pj&p_sid=pHYE0ib&p_uid=fTs1FtIIjO&ss=paid&utm_campaign=cs_2024&utm_content=pj_board&utm_medium=jobad&utm_source=indeed",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "NextCentury Submetering Solutions",
    foundAt: "indeed",
    role: "Senior Software Engineeer",
    website:
      "https://jobs.gusto.com/postings/next-meters-senior-software-engineer-bc0e2d5b-2861-475b-9b59-19eca4074137",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Bill",
    foundAt: "indeed",
    role: "Senior Software Engineer (Backend) - Identity",
    website:
      "https://www.indeed.com/jobs?q=software+engineer&l=Ogden%2C+UT&from=searchOnHP&vjk=6f4231851597b8cf",
    status: "Rejected",
    rejectedAt: "6/21/24",
    appliedAt: "6/10/24",
    salary: {
      min: 123800,
      max: 148500,
    },
  },
  {
    name: "SymLiv",
    foundAt: "indeed",
    role: "Senior Software Engineer",
    website: "https://www.indeed.com/",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Porch Software",
    foundAt: "indeed",
    role: "Mid/Senior Backend Software Engineer",
    website: "https://www.indeed.com/",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Lifetime",
    foundAt: "indeed",
    role: "Software Developer",
    website:
      "https://www.indeed.com/cmp/Lifetime-Products,-Inc.?from=mobviewjob&tk=1hvo1ukldln3n801&fromjk=1e9d4f021ef94123&attributionid=mobvjcmp",
    status: "Rejected",
    appliedAt: "6/6/24",
    rejectedAt: "6/11/24",
  },
  {
    name: "Trenchant Analytics, LLC",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/5/24",
  },
  {
    name: "SSi People",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/5/24",
  },
  {
    name: "Aura Recruit Ltd.",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/5/24",
  },
  {
    name: "BloomTech",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "https://www.bloomtech.com",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "ARK Solutions, Inc",
    foundAt: "linkedin",
    role: "Front-End Engineer (REMOTE)",
    website: "https://arksolutionsinc.com/",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Microsoft",
    foundAt: "linkedin",
    role: "Software Development Engineer II (1715397)",
    website:
      "https://jobs.careers.microsoft.com/global/en/apply/thankyou?Job_id=1715397",
    status: "Applied",
    appliedAt: "6/2/24",
    salary: {
      min: 120900,
      max: 198600,
    },
  },
  {
    name: "Sheldon Whispers",
    foundAt: "linkedin",
    role: "Full Stack Software Engineer (React, .NET Core, Azure)",
    website: "https://www.sheldonwhispers.com",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "HireHeroes.ai",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://hireheroes.ai/",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Oracle",
    foundAt: "linkedin",
    role: "Software Developer 2",
    website:
      "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/my-profile",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Engtal",
    foundAt: "linkedin",
    role: "Entry Level Software Engineer (Remote)",
    website: "https://engtal.com",
    status: "Applied",
    appliedAt: "6/1/24",
  },
  {
    name: "Honor",
    foundAt: "commitasync",
    role: "Senior Software Engineer (Workforce)",
    website: "joinhonor.com",
    status: "Applied",
    appliedAt: "5/31/24",
    rejectedAt: "6/3/24",
  },
  {
    name: "Foodsmart",
    foundAt: "commitasync",
    role: "Senior Software Engineer",
    website: "foodsmart.com",
    status: "Applied",
    appliedAt: "5/31/24",
  },
  {
    name: "HubSpot",
    foundAt: "commitasync",
    role: "Software Engineer (USA)",
    website: "hubspot.com",
    status: "Rejected",
    appliedAt: "5/31/24",
    rejectedAt: "6/4/24",
  },
  {
    name: "SocialHub",
    foundAt: "wellfound",
    role: "Backend Javascript/Node.js Developer",
    website: "socialhub.io",
    status: "Rejected",
    appliedAt: "5/21/24",
    rejectedAt: "5/31/24",
  },
  {
    name: "Aquent",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "aquent.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "Avionte Staffing Software",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "avionte.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "MPCH",
    foundAt: "linkedin",
    role: "Junior Full Stack Engineer",
    website: "mpch.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "BotDojo",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "botdojo.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "eTeam",
    foundAt: "linkedin",
    role: "Javascript Developer",
    website: "eteaminc.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "TekJobs",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "tekjobs.net",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "24 Sevent Talent",
    foundAt: "linkedin",
    role: "Full Stack Developer",
    website: "24seventalent.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "Sticker Mule",
    foundAt: "wellfound",
    role: "Software Engineer (Backend)",
    website: "stickermule.com",
    status: "Rejected",
    appliedAt: "5/22/24",
    rejectedAt: "5/30/24",
  },
  {
    name: "DASH2",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "dash2group.com",
    status: "Applied",
    appliedAt: "5/29/24",
  },
  {
    name: "Demandbase",
    foundAt: "commitasync",
    role: "Full Stack Engineer",
    website: "https://www.demandbase.com",
    status: "Rejected",
    appliedAt: "5/28/24",
    rejectedAt: "6/14/24",
  },
  {
    name: "eTeam",
    foundAt: "linkedin",
    role: "Staff Software Engineer",
    website: "eteaminc.com",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "ACS Consultancy Services, Inc",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "eteaminc.com",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "Private Client",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "linkedin",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "Phamily",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "phamily.com",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "InstaService",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "linkedin",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "Rec",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "wellfound",
    status: "Applied",
    appliedAt: "5/21/24",
    rejectedAt: "5/22/24",
  },
  {
    name: "BreezeRFP",
    foundAt: "wellfound",
    role: "Founding Engineer (Mid-Level)",
    website: "https://boards.greenhouse.io/wondersco?t=bb6e7d056us",
    status: "Applied",
    appliedAt: "5/21/24",
    rejectedAt: "5/22/24",
  },
  {
    name: "Recurate",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "recurate.com",
    status: "Applied",
    appliedAt: "5/22/24",
  },
  {
    name: "Rye",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://www.rye.com",
    status: "Rejected",
    appliedAt: "5/22/24",
    rejectedAt: "6/3/24",
  },
  {
    name: "DevZero",
    foundAt: "wellfound",
    role: "Full-stack Developer",
    website: "https://www.devzero.io/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Pistachio",
    foundAt: "wellfound",
    role: "Full-stack Developer",
    website: "wellfound",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Bite",
    foundAt: "wellfound",
    role: "Full-Stack Software Engineer",
    website: "getbite.com",
    status: "Rejected",
    appliedAt: "5/21/24",
    rejectedAt: "6/5/24",
  },
  {
    name: "Truckbase",
    foundAt: "wellfound",
    role: "Product Engineer",
    website: "truckbase.com",
    status: "Rejected",
    appliedAt: "5/21/24",
  },
  {
    name: "Fieldwire",
    foundAt: "wellfound",
    role: "Mid-Level Fullstack Engineer",
    website: "fieldwire.com",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Cinder",
    foundAt: "wellfound",
    role: "Senior Software Engineer - Full Stack",
    website: "cndr.io",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Churnkey",
    foundAt: "wellfound",
    role: "Senior Full-Stack Engineer",
    website: "churnkey.co",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Hedge",
    foundAt: "wellfound",
    role: "Full-Stack Engineer",
    website: "hedge.io",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Cyrisma",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "cyrisma.com",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Onestop Software",
    foundAt: "linkedin",
    role: "Javascript Developer",
    website: "onestop.software",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Technology Group Inc (US)",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://intechnologygroup.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Innovaccer",
    foundAt: "linkedin",
    role: "Software Engineer II",
    website: "https://innovaccer.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Enigma",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://enigma.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Scope Labs",
    foundAt: "wellfound",
    role: "Full-Stack Engineer",
    website: "https://scopelabs.com/",
    status: "Assessment",
    appliedAt: "5/21/24",
    assessmentAt: "6/11/24",
    salary: {
      min: 120000,
      max: 160000,
    },
  },
  {
    name: "AllSpice.io",
    foundAt: "wellfound",
    role: "Lead Fullstack Engineer",
    website: "https://allspice.io/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Breadcrumb",
    foundAt: "wellfound",
    role: "Lead Fullstack Engineer",
    assessmentAt: "5/29/24",
    website: "https://www.breadcrumb.ai/",
    status: "Assessment",
    appliedAt: "5/21/24",
  },
  {
    name: "Abnormal Security",
    foundAt: "wellfound",
    role: "Software Engineer",
    website: "https://abnormalsecurity.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Zillow",
    foundAt: "linkedin",
    role: "Senior Software Development Engineer",
    website: "https://zillow.com/",
    status: "Rejected",
    appliedAt: "5/21/24",
    rejectedAt: "6/18/24",
  },
  {
    name: "Jellyfish",
    foundAt: "linkedin",
    role: "Backend Engineer",
    website: "https://jellyfish.co/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Storm2",
    foundAt: "linkedin",
    role: "Software Engineer (Fin-Tech)",
    website: "https://linkedin/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Motion Recruitment",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "https://motionrecruitment.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "ByteBrew",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://bytebrew.io/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Flawless",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.flawlessrecruit.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
];
