import { Application } from "./types";

export const applications: Application[] = [
  {
    name: "Braintrust",
    foundAt: "linkedin",
    role: "API ENgineer - 587",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "True Group, Inc.",
    foundAt: "linkedin",
    role: ".NET Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "AshedIre Inc",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "IDR, Inc.",
    foundAt: "linkedin",
    role: "React Developer (9338779)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "MMD Services",
    foundAt: "linkedin",
    role: "Full Stack Engineer (React/Node) - Logistics",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Kress Designs Inc.",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Hopper",
    foundAt: "linkedin",
    role: "Software Developer, Full Stack/Mobile",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Strategic Employment Partners (SEP)",
    foundAt: "linkedin",
    role: "Fullstack .NET Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Recruiting From Scratch",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "rheumission",
    foundAt: "linkedin",
    role: "Full Stack Systems Engineer/Architect",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Tamnoon",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "22nd Century Technologies Inc.",
    foundAt: "linkedin",
    role: "Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "System Soft Technologies",
    foundAt: "linkedin",
    role: "Ecommerce Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Flintfox - Intelligent Pricing Platform",
    foundAt: "linkedin",
    role: ".NET Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Z. Wilson Talent Solutions",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Insurity",
    foundAt: "indeed",
    role: "Developer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Servpro",
    foundAt: "indeed",
    role: "Senior Developer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "EDZ Systems",
    foundAt: "indeed",
    role: "Site Reliability Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Northrop Grumman",
    foundAt: "indeed",
    role: "Sentinel Software Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Stratagen",
    foundAt: "indeed",
    role: "Software Developer 2",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "OneFifteen Recovery",
    foundAt: "indeed",
    role: "Senior Software Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Credit Corp Solutions",
    foundAt: "indeed",
    role: "Full Stack Developer - .Net",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "SOLUTIONREACH, INC.",
    foundAt: "indeed",
    role: "Principal Quality Engineer",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Talent Groups",
    foundAt: "linkedin",
    role: ".Net Developer (UT Residents Only)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/19/24",
  },
  {
    name: "Clicklease",
    foundAt: "indeed",
    role: "Software Architect",
    website: "https://www.indeed.com",
    status: "Rejected",
    appliedAt: "6/15/24",
    rejectedAt: "6/18/24",
  },
  {
    name: "Signify Technology",
    foundAt: "linkedin",
    role: "Senior Frontend Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Stealth",
    foundAt: "linkedin",
    role: "Backend Engineer - Node.js/TypeScript",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Cygnus Professionals Inc.",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Goliath Partners",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Torticity",
    foundAt: "linkedin",
    role: "Full Stack Javascript Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "MMD Services",
    foundAt: "linkedin",
    role: "Senior Full-Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Cart.com",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Empiric",
    foundAt: "linkedin",
    role: "Associate .Net Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Allyon, Inc.",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Kadince",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "ALIGNMT ai",
    foundAt: "linkedin",
    role: "Founding Software Engineer, Frontend",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "IntegraWeb Systems",
    foundAt: "linkedin",
    role: "Full Stack Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/12/24",
  },
  {
    name: "Estes Group, LLC.",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Bigtoe Pose, Inc.",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Curate Partners",
    foundAt: "linkedin",
    role: "Full Stack Engineer (Data Science focus)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Saroe, Inc",
    foundAt: "linkedin",
    role: "Backend Integration Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "BlackLake Security",
    foundAt: "linkedin",
    role: "Senior Full-Stack Software Engineer - Contract",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Nelson Connects",
    foundAt: "linkedin",
    role: "Founding Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Fiori Technology Solutions Inc",
    foundAt: "linkedin",
    role: "C# Developer/Programmer Analyst",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Planet Technology",
    foundAt: "linkedin",
    role: "Developer Evangelist - Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Fieldwire",
    foundAt: "linkedin",
    role: "Mid-Level Frontend Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Verdantas",
    foundAt: "linkedin",
    role: "Application Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "VoteBud",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Clinical AI",
    foundAt: "linkedin",
    role: "Software Engineer I",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Entelli Consulting",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Tangerine Search Inc.",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Raydar",
    foundAt: "linkedin",
    role: "Solutions Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Plexus Resource Solutions",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Robert Half",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Associated Wholesale Grocers",
    foundAt: "linkedin",
    role: "SaaS Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Insight Global",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Cohere Health",
    foundAt: "linkedin",
    role: "Software Engineer II, Applications",
    website: "https://www.linkedin.com",
    status: "Rejected",
    appliedAt: "6/11/24",
    rejectedAt: "6/13/24",
  },
  {
    name: "Engtal",
    foundAt: "linkedin",
    role: "Entry Level Software Engineer (Remote)",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Accelon Inc",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Alpine Solutions Group",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Dockyard, Inc",
    foundAt: "direct",
    role: "Senior Software Engineer (Typescript)",
    website:
      "https://dockyard.breezy.hr/p/94c49049786f-senior-software-engineer-typescript/apply/submitted",
    status: "Rejected",
    appliedAt: "6/11/24",
    rejectedAt: "6/13/24",
  },
  {
    name: "Canny",
    foundAt: "direct",
    role: "Software Engineer (Remote)",
    website:
      "https://careers.canny.io/o/software-engineer-remote-2-11/c/new?source=LinkedIn",
    status: "Assessment",
    appliedAt: "6/11/24",
    assessmentAt: "6/13/24",
  },
  {
    name: "Clickhouse",
    foundAt: "direct",
    role: "Full Stack Engineer - Billing (Remote)",
    website: "https://clickhouse.com/company/careers",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Clickhouse",
    foundAt: "direct",
    role: "Cloud Software Engineer, Developer Productivity- Remote",
    website: "https://clickhouse.com/company/careers",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Clublender",
    foundAt: "weworkremotely",
    role: "FullStack Software Developer",
    website:
      "https://weworkremotely.com/remote-jobs/clublender-inc-full-stack-web-developer-1",
    status: "Applied",
    appliedAt: "6/11/24",
  },
  {
    name: "Stratagen",
    foundAt: "indeed",
    role: "Software Developer 3",
    website: "https://www.indeed.com/cmp/Stratagen-1?attributionid=IAconfirm",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Thrive Market",
    foundAt: "commitasync",
    role: "Senior Software Engineer, Web",
    website: "https://thrivemarket.com/",
    status: "Rejected",
    appliedAt: "6/10/24",
    rejectedAt: "6/17/24",
  },
  {
    name: "Khan Academy",
    foundAt: "commitasync",
    role: "Software Engineer II, Data Infrastructure",
    website: "https://boards.greenhouse.io/khanacademy/jobs/6005599",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "KarmaCheck",
    foundAt: "indeed",
    role: "Sr Software Engineer - Frontend",
    website: "https://www.indeed.com",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "L3Harris",
    foundAt: "indeed",
    role: "Specialist, Software Engineer",
    website:
      "https://careers.l3harris.com/job/-/-/4832/66137134304?jobPipeline=rd_indeed_pj&p_sid=pHYE0ib&p_uid=fTs1FtIIjO&ss=paid&utm_campaign=cs_2024&utm_content=pj_board&utm_medium=jobad&utm_source=indeed",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "NextCentury Submetering Solutions",
    foundAt: "indeed",
    role: "Senior Software Engineeer",
    website:
      "https://jobs.gusto.com/postings/next-meters-senior-software-engineer-bc0e2d5b-2861-475b-9b59-19eca4074137",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Bill",
    foundAt: "indeed",
    role: "Senior Software Engineer (Backend) - Identity",
    website:
      "https://www.indeed.com/jobs?q=software+engineer&l=Ogden%2C+UT&from=searchOnHP&vjk=6f4231851597b8cf",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "SymLiv",
    foundAt: "indeed",
    role: "Senior Software Engineer",
    website: "https://www.indeed.com/",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Porch Software",
    foundAt: "indeed",
    role: "Mid/Senior Backend Software Engineer",
    website: "https://www.indeed.com/",
    status: "Applied",
    appliedAt: "6/10/24",
  },
  {
    name: "Lifetime",
    foundAt: "indeed",
    role: "Software Developer",
    website:
      "https://www.indeed.com/cmp/Lifetime-Products,-Inc.?from=mobviewjob&tk=1hvo1ukldln3n801&fromjk=1e9d4f021ef94123&attributionid=mobvjcmp",
    status: "Rejected",
    appliedAt: "6/6/24",
    rejectedAt: "6/11/24",
  },
  {
    name: "Trenchant Analytics, LLC",
    foundAt: "linkedin",
    role: "Senior Software Engineer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/5/24",
  },
  {
    name: "SSi People",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/5/24",
  },
  {
    name: "Aura Recruit Ltd.",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "https://www.linkedin.com",
    status: "Applied",
    appliedAt: "6/5/24",
  },
  {
    name: "BloomTech",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "https://www.bloomtech.com",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "ARK Solutions, Inc",
    foundAt: "linkedin",
    role: "Front-End Engineer (REMOTE)",
    website: "https://arksolutionsinc.com/",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Microsoft",
    foundAt: "linkedin",
    role: "Software Development Engineer II (1715397)",
    website:
      "https://jobs.careers.microsoft.com/global/en/apply/thankyou?Job_id=1715397",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Sheldon Whispers",
    foundAt: "linkedin",
    role: "Full Stack Software Engineer (React, .NET Core, Azure)",
    website: "https://www.sheldonwhispers.com",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "HireHeroes.ai",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "https://hireheroes.ai/",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Oracle",
    foundAt: "linkedin",
    role: "Software Developer 2",
    website:
      "https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/my-profile",
    status: "Applied",
    appliedAt: "6/2/24",
  },
  {
    name: "Engtal",
    foundAt: "linkedin",
    role: "Entry Level Software Engineer (Remote)",
    website: "https://engtal.com",
    status: "Applied",
    appliedAt: "6/1/24",
  },
  {
    name: "Honor",
    foundAt: "commitasync",
    role: "Senior Software Engineer (Workforce)",
    website: "joinhonor.com",
    status: "Applied",
    appliedAt: "5/31/24",
    rejectedAt: "6/3/24",
  },
  {
    name: "Foodsmart",
    foundAt: "commitasync",
    role: "Senior Software Engineer",
    website: "foodsmart.com",
    status: "Applied",
    appliedAt: "5/31/24",
  },
  {
    name: "HubSpot",
    foundAt: "commitasync",
    role: "Software Engineer (USA)",
    website: "hubspot.com",
    status: "Rejected",
    appliedAt: "5/31/24",
    rejectedAt: "6/4/24",
  },
  {
    name: "SocialHub",
    foundAt: "wellfound",
    role: "Backend Javascript/Node.js Developer",
    website: "socialhub.io",
    status: "Rejected",
    appliedAt: "5/21/24",
    rejectedAt: "5/31/24",
  },
  {
    name: "Aquent",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "aquent.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "Avionte Staffing Software",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "avionte.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "MPCH",
    foundAt: "linkedin",
    role: "Junior Full Stack Engineer",
    website: "mpch.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "BotDojo",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "botdojo.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "eTeam",
    foundAt: "linkedin",
    role: "Javascript Developer",
    website: "eteaminc.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "TekJobs",
    foundAt: "linkedin",
    role: "Frontend Developer",
    website: "tekjobs.net",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "24 Sevent Talent",
    foundAt: "linkedin",
    role: "Full Stack Developer",
    website: "24seventalent.com",
    status: "Applied",
    appliedAt: "5/30/24",
  },
  {
    name: "Sticker Mule",
    foundAt: "wellfound",
    role: "Software Engineer (Backend)",
    website: "stickermule.com",
    status: "Rejected",
    appliedAt: "5/22/24",
    rejectedAt: "5/30/24",
  },
  {
    name: "DASH2",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "dash2group.com",
    status: "Applied",
    appliedAt: "5/29/24",
  },
  {
    name: "Demandbase",
    foundAt: "direct",
    role: "Full Stack Engineer",
    website: "https://www.demandbase.com",
    status: "Rejected",
    appliedAt: "5/28/24",
    rejectedAt: "6/14/24",
  },
  {
    name: "eTeam",
    foundAt: "linkedin",
    role: "Staff Software Engineer",
    website: "eteaminc.com",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "ACS Consultancy Services, Inc",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "eteaminc.com",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "Private Client",
    foundAt: "linkedin",
    role: "Web Developer",
    website: "linkedin",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "Phamily",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "phamily.com",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "InstaService",
    foundAt: "linkedin",
    role: "Software Engineer",
    website: "linkedin",
    status: "Applied",
    appliedAt: "5/27/24",
  },
  {
    name: "Rec",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "wellfound",
    status: "Applied",
    appliedAt: "5/21/24",
    rejectedAt: "5/22/24",
  },
  {
    name: "BreezeRFP",
    foundAt: "wellfound",
    role: "Founding Engineer (Mid-Level)",
    website: "https://boards.greenhouse.io/wondersco?t=bb6e7d056us",
    status: "Applied",
    appliedAt: "5/21/24",
    rejectedAt: "5/22/24",
  },
  {
    name: "Recurate",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "recurate.com",
    status: "Applied",
    appliedAt: "5/22/24",
  },
  {
    name: "Rye",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://www.rye.com",
    status: "Rejected",
    appliedAt: "5/22/24",
    rejectedAt: "6/3/24",
  },
  {
    name: "DevZero",
    foundAt: "wellfound",
    role: "Full-stack Developer",
    website: "https://www.devzero.io/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Pistachio",
    foundAt: "wellfound",
    role: "Full-stack Developer",
    website: "wellfound",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Bite",
    foundAt: "wellfound",
    role: "Full-Stack Software Engineer",
    website: "getbite.com",
    status: "Rejected",
    appliedAt: "5/21/24",
    rejectedAt: "6/5/24",
  },
  {
    name: "Truckbase",
    foundAt: "wellfound",
    role: "Product Engineer",
    website: "truckbase.com",
    status: "Rejected",
    appliedAt: "5/21/24",
  },
  {
    name: "Fieldwire",
    foundAt: "wellfound",
    role: "Mid-Level Fullstack Engineer",
    website: "fieldwire.com",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Cinder",
    foundAt: "wellfound",
    role: "Senior Software Engineer - Full Stack",
    website: "cndr.io",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Churnkey",
    foundAt: "wellfound",
    role: "Senior Full-Stack Engineer",
    website: "churnkey.co",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Hedge",
    foundAt: "wellfound",
    role: "Full-Stack Engineer",
    website: "hedge.io",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Cyrisma",
    foundAt: "linkedin",
    role: "Software Developer",
    website: "cyrisma.com",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Onestop Software",
    foundAt: "linkedin",
    role: "Javascript Developer",
    website: "onestop.software",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Technology Group Inc (US)",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://intechnologygroup.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Innovaccer",
    foundAt: "linkedin",
    role: "Software Engineer II",
    website: "https://innovaccer.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Enigma",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://enigma.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Enigma",
    foundAt: "wellfound",
    role: "Senior Full Stack Engineer",
    website: "https://enigma.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Scope Labs",
    foundAt: "wellfound",
    role: "Full-Stack Engineer",
    website: "https://scopelabs.com/",
    status: "Assessment",
    appliedAt: "5/21/24",
    assessmentAt: "6/11/24",
  },
  {
    name: "AllSpice.io",
    foundAt: "wellfound",
    role: "Lead Fullstack Engineer",
    website: "https://allspice.io/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Breadcrumb",
    foundAt: "wellfound",
    role: "Lead Fullstack Engineer",
    assessmentAt: "5/29/24",
    website: "https://www.breadcrumb.ai/",
    status: "Assessment",
    appliedAt: "5/21/24",
  },
  {
    name: "Abnormal Security",
    foundAt: "wellfound",
    role: "Software Engineer",
    website: "https://abnormalsecurity.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Zillow",
    foundAt: "linkedin",
    role: "Senior Software Development Engineer",
    website: "https://zillow.com/",
    status: "Rejected",
    appliedAt: "5/21/24",
    rejectedAt: "6/18/24",
  },
  {
    name: "Jellyfish",
    foundAt: "linkedin",
    role: "Backend Engineer",
    website: "https://jellyfish.co/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Storm2",
    foundAt: "linkedin",
    role: "Software Engineer (Fin-Tech)",
    website: "https://linkedin/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Motion Recruitment",
    foundAt: "linkedin",
    role: "Back End Developer",
    website: "https://motionrecruitment.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "ByteBrew",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://bytebrew.io/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
  {
    name: "Flawless",
    foundAt: "linkedin",
    role: "Full Stack Engineer",
    website: "https://www.flawlessrecruit.com/",
    status: "Applied",
    appliedAt: "5/21/24",
  },
];
